on:
  push:
    branches:
      - main


permissions:
  contents: write

jobs:
  push-to-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git push origin HEAD:staging
      - run: git push origin HEAD:production
