on:
  push:
    branches:
      - main

jobs:
  push-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git push origin HEAD:staging
      - run: git push origin HEAD:production
